void alarm_handler();
char *getPort(int port);
int setTermios(int fd);
int llopen(int port, int flag);
void llopenRCVCV(int fd);
void llopenSND(int fd);
int llwrite(int fd, char *buffer, int length);
int llread(int fd, char *buffer);
int llcloseSND(int fd, int flag);
int receivedDISCframeRCV();
int llcloseRCV(int fd, int flag);